import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getSortedPostsData } from "../lib/posts";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="">
          <ul>
            <li>David Gordon </li>
          </ul>
        </nav>
        <section>
          <p>
            Hi there! My name is David and I am a full stack web developer. I
            love building websites that not only look great, but are also easy
            to use and navigate. In my free time, I enjoy making art, going to
            the gym, and spending time with my furry best friend, Merlin.
            I&apos;m always looking for new ways to improve my skills and take
            on new challenges, so if you have a project that you think I might
            be interested in, don&apos;t hesitate to reach out!
          </p>
        </section>
        <section>
          <h2>Blog</h2>
          <ul>
            {allPostsData.map(({ id, date, title }: any) => (
              <li key={id}>
                {title}
                <br />
                {id}
                <br />
                {date}
              </li>
            ))}
          </ul>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
